from typing import Final

CHUNK_SIZE: Final = 1024 * 1024  # 1Mb
BOT_API_VERSION: Final = 4
SMARTAPP_API_VERSION: Final = 1
STICKER_IMAGE_MAX_SIZE: Final = 512 * 1024  # 512Kb
STICKER_PACKS_PER_PAGE: Final = 10
MAX_NOTIFICATION_BODY_LENGTH: Final = 4096
MAX_FILE_LEN_IN_LOGS: Final = 64
BOTX_DEFAULT_TIMEOUT: Final = 60

BOTX_HTTP_CONNECT_TIMEOUT_SECONDS: Final = 3.0
BOTX_HTTP_READ_TIMEOUT_SECONDS: Final = 30.0
BOTX_HTTP_WRITE_TIMEOUT_SECONDS: Final = 10.0
BOTX_HTTP_POOL_TIMEOUT_SECONDS: Final = 1.0

BOTX_HTTP_MAX_CONNECTIONS: Final = 500
BOTX_HTTP_MAX_KEEPALIVE_CONNECTIONS: Final = 100
BOTX_HTTP_KEEPALIVE_EXPIRY_SECONDS: Final = 30.0

BOTX_HTTP_RETRY_ATTEMPTS: Final = 4
BOTX_HTTP_RETRY_INITIAL_DELAY_SECONDS: Final = 0.2
BOTX_HTTP_RETRY_MAX_DELAY_SECONDS: Final = 5.0
BOTX_HTTP_RETRY_JITTER_SECONDS: Final = 0.2

BOTX_COMMAND_PROCESSING_MAX_CONCURRENCY: Final = 100
BOTX_COMMAND_PROCESSING_MAX_QUEUE_SIZE: Final = 1000
