image: docker:latest

before_script:
  - docker info

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - docker build --force-rm -t $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG} .