dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"

install:
    - pip install poetry
    - poetry config settings.virtualenvs.create false
    - poetry install

script:
    - bash scripts/test.sh
