site_name: pybotx-next
site_url: !!python/object/apply:os.getenv ["SITE_URL", "https://expressapp.github.io/pybotx-next"]
site_description: A little python library for building bots for Express

theme:
  name: "material"

repo_name: ExpressApp/pybotx
repo_url: https://github.com/ExpressApp/pybotx
edit_uri: ''

nav:
  - Introduction: 'index.md'
  - Full Guide: 'guide.md'
  - BotX API: 'botx_api.md'
  - Architecture: 'architecture.md'
  - Dependency Injection: 'di.md'
  - Bot API: 'bot.md'
  - Bot Command Link: 'bot_command_link.md'
  - Builders and Options: 'builders.md'
  - Bulk Operations: 'bulk.md'
  - Widgets: 'widgets.md'
  - Widgets Guide: 'widgets_guide.md'
  - Text Builder: 'text.md'
  - Attachments: 'attachments.md'
  - HTTP and Retry: 'http.md'
  - Adapters: 'adapters.md'
  - Todo Bot Example: 'examples_todo.md'
  - Migration: 'migration.md'
  - FAQ / Best Practices: 'faq.md'

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
  - codehilite:
      css_class: highlight

extra_css:
  - css/custom.css
