site_name: pybotx
site_description: A little python library for building bots for Express

theme:
    name: 'material'

repo_name: ExpressApp/pybotx
repo_url: https://github.com/ExpressApp/pybotx
edit_uri: ''

nav:
    - Introduction: 'index.md'
    - Tutorial - User Guide:
        - First Steps: 'development/first-steps.md'
        - Sending Messages And Files: 'development/sending-data.md'
        - HandlersCollector: 'development/handlers-collector.md'
        - Developing Using Tokens: 'development/cts-tokens.md'
        - Deployment: 'development/bots-deployment.md'
    - API Reference:
        - Bots: 'api-reference/bots.md'
        - HandlersCollector: 'api-reference/handlers-collector.md'
        - BotX Types: 'api-reference/botx-types.md'
    - Changelog: 'changelog.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition