from string import Template


GITIGNORE_TEMPLATE = Template(
    """__pycache__/
.mypy_cache/
.pytest_cache/
.ruff_cache/
.venv/
dist/
build/
*.pyc
.env
"""
)


ENV_EXAMPLE_TEMPLATE = Template(
    """BOT_ID="123e4567-e89b-12d3-a456-426655440000"
BOT_CTS_URL="https://cts.example.com"
BOT_SECRET_KEY="replace-with-real-secret"

BOT_DISPLAY_NAME="$display_name"

BOT_COMMAND_MAX_CONCURRENCY="32"
BOT_COMMAND_MAX_QUEUE_SIZE="512"
BOT_COMMAND_OVERLOAD_ACTION="reject_new"

BOT_ENABLE_OTEL_TRACING="${enable_otel_tracing}"
BOT_OTEL_TRACER_NAME="$package_name.bot"
"""
)


ENV_EXAMPLE_FSM_TEMPLATE = Template(
    """BOT_ID="123e4567-e89b-12d3-a456-426655440000"
BOT_CTS_URL="https://cts.example.com"
BOT_SECRET_KEY="replace-with-real-secret"

BOT_DISPLAY_NAME="$display_name"

BOT_COMMAND_MAX_CONCURRENCY="32"
BOT_COMMAND_MAX_QUEUE_SIZE="512"
BOT_COMMAND_OVERLOAD_ACTION="reject_new"

BOT_ENABLE_OTEL_TRACING="${enable_otel_tracing}"
BOT_OTEL_TRACER_NAME="$package_name.bot"

BOT_FSM_REDIS_URL="redis://localhost:6379/0"
BOT_FSM_STATE_TTL_SECONDS="900"
"""
)


README_TEMPLATE = Template(
    """# $project_name

Production-ready `pybotx` bot scaffold generated by `pybotx create bot`.

## What is included

- FastAPI integration for `/command`, `/status`, `/notification/callback`
- library-owned FastAPI adapter from `pybotx`
- `/metrics` with shared Prometheus registry
- `pybotx` production bot preset
- structured JSON logs from `pybotx`
- healthcheck endpoints from `pybotx`
- command processing limits and backpressure config
- `dependency-injector` container
- 4-layer clean architecture: `domain / application / infrastructure / presentation`
- sample domain port and repository stub wired through DI
- sample `/start` and `/help` commands
- pytest/ruff/mypy configuration

## Setup

```bash
uv sync
cp .env.example .env
```

Fill real values in `.env`:

- `BOT_ID`
- `BOT_CTS_URL`
- `BOT_SECRET_KEY`

Optional:

- `BOT_ENABLE_OTEL_TRACING=true` if you want OpenTelemetry tracing

## Run

```bash
uv run uvicorn $package_name.main:app --host 0.0.0.0 --port 8000 --reload
```

## Docker

```bash
docker compose up --build
```

## Add a command

```bash
uv run pybotx create command ping-users --project-dir .
```

## Add an application service

```bash
uv run pybotx create service sync-users --project-dir .
```

## Add a port

```bash
uv run pybotx create port billing-gateway --project-dir .
```

## Add a repository

```bash
uv run pybotx create repository user-profile --project-dir .
```

To bind a repository stub to an existing port:

```bash
uv run pybotx create repository stripe-billing-gateway --project-dir . --port billing-gateway
```

## Add a widget

```bash
uv run pybotx create widget deployment-approval --project-dir . --kind confirm
```

## Add a widget flow

```bash
uv run pybotx create widget-flow deployment-approval --project-dir . --kind confirm
```

## Endpoints

- `POST /command`
- `GET /status`
- `POST /notification/callback`
- `GET /metrics`
- `GET /health/`
- `GET /health/ready`

## Architecture

- Layering rules and examples live in `ARCHITECTURE.md`
- Composition root lives in `src/$package_name/container.py`
- `pybotx` handlers stay in `src/$package_name/presentation/`
- application services live in `src/$package_name/application/services/`
- domain ports live in `src/$package_name/domain/ports/`
- repository implementations live in `src/$package_name/infrastructure/repositories/`

## Tests

```bash
uv run pytest
uv run ruff check .
uv run mypy src tests
```
"""
)


README_FSM_TEMPLATE = Template(
    """# $project_name

Production-ready `pybotx` + `pybotx-fsm` bot scaffold generated by `pybotx create bot`.

## What is included

- FastAPI integration for `/command`, `/status`, `/notification/callback`
- library-owned FastAPI adapter from `pybotx`
- `/metrics` with shared Prometheus registry
- `pybotx` production bot preset
- `pybotx-fsm` middleware and sample login flow
- `RedisFSMStateRepo` for FSM state persistence
- readiness check for Redis-backed FSM storage
- structured JSON logs from `pybotx`
- healthcheck endpoints from `pybotx`
- command processing limits and backpressure config
- `dependency-injector` container
- 4-layer clean architecture: `domain / application / infrastructure / presentation`
- sample domain port and repository stub wired through DI
- sample `/start`, `/help`, `/login`, `/cancel` commands
- pytest/ruff/mypy configuration

## Setup

```bash
uv sync
cp .env.example .env
```

Fill real values in `.env`:

- `BOT_ID`
- `BOT_CTS_URL`
- `BOT_SECRET_KEY`
- `BOT_FSM_REDIS_URL`

Optional:

- `BOT_ENABLE_OTEL_TRACING=true` if you want OpenTelemetry tracing

## Run

```bash
uv run uvicorn $package_name.main:app --host 0.0.0.0 --port 8000 --reload
```

## Docker

```bash
docker compose up --build
```

## Add a command

```bash
uv run pybotx create command ping-users --project-dir .
```

## Add an application service

```bash
uv run pybotx create service sync-users --project-dir .
```

## Add a port

```bash
uv run pybotx create port billing-gateway --project-dir .
```

## Add a repository

```bash
uv run pybotx create repository user-profile --project-dir .
```

To bind a repository stub to an existing port:

```bash
uv run pybotx create repository stripe-billing-gateway --project-dir . --port billing-gateway
```

## Add an FSM flow

```bash
uv run pybotx create fsm-flow approval --project-dir .
```

## Add a widget

```bash
uv run pybotx create widget deployment-approval --project-dir . --kind confirm
```

## Add a widget flow

```bash
uv run pybotx create widget-flow deployment-approval --project-dir . --kind confirm
```

## Endpoints

- `POST /command`
- `GET /status`
- `POST /notification/callback`
- `GET /metrics`
- `GET /health/`
- `GET /health/ready`

## Architecture

- Layering rules and examples live in `ARCHITECTURE.md`
- Composition root lives in `src/$package_name/container.py`
- `pybotx` handlers and FSM flows live in `src/$package_name/presentation/`
- Redis-backed FSM storage lives in `src/$package_name/infrastructure/`
- domain ports live in `src/$package_name/domain/ports/`
- repository implementations live in `src/$package_name/infrastructure/repositories/`

## FSM demo

Send `/login`, then use:

- `demo@example.com`
- `password123`

## Tests

```bash
uv run pytest
uv run ruff check .
uv run mypy src tests
```
"""
)


PYPROJECT_TEMPLATE = Template(
    """[project]
name = "$project_name"
version = "0.1.0"
description = "$description"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "pybotx==$pybotx_version",
    "dependency-injector>=4.48.1,<5",
    "fastapi>=0.128.0,<0.129",
    "opentelemetry-api>=1.38.0,<2",
    "prometheus-client>=0.22.1,<0.23",
    "pydantic-settings>=2.10.1,<3",
    "uvicorn>=0.40.0,<0.41",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1,<2",
    "pytest>=9.0.2,<10",
    "pytest-asyncio>=1.3.0,<2",
    "ruff>=0.15.0,<0.16",
]

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/$package_name"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.mypy]
python_version = "3.10"
strict = true
mypy_path = ["src"]
"""
)


PYPROJECT_FSM_TEMPLATE = Template(
    """[project]
name = "$project_name"
version = "0.1.0"
description = "$description"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "pybotx==$pybotx_version",
    "pybotx-fsm>=0.6.1,<0.7",
    "dependency-injector>=4.48.1,<5",
    "fastapi>=0.128.0,<0.129",
    "opentelemetry-api>=1.38.0,<2",
    "prometheus-client>=0.22.1,<0.23",
    "pydantic-settings>=2.10.1,<3",
    "redis>=5.0.0,<6",
    "uvicorn>=0.40.0,<0.41",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1,<2",
    "pytest>=9.0.2,<10",
    "pytest-asyncio>=1.3.0,<2",
    "ruff>=0.15.0,<0.16",
]

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/$package_name"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.mypy]
python_version = "3.10"
strict = true
mypy_path = ["src"]
"""
)


PACKAGE_INIT_TEMPLATE = Template(
    '''"""$display_name bot package."""\n'''
)


DOMAIN_INIT_TEMPLATE = Template(
    '"""Domain layer: pure business models, rules, and contracts."""\n',
)


DOMAIN_PORTS_INIT_TEMPLATE = Template(
    '"""Domain ports: contracts that infrastructure implements."""\n',
)


APPLICATION_INIT_TEMPLATE = Template(
    '"""Application layer: use cases and orchestration."""\n',
)


APPLICATION_PORTS_INIT_TEMPLATE = Template(
    '"""Application ports: use-case level contracts for outbound dependencies."""\n',
)


INFRASTRUCTURE_INIT_TEMPLATE = Template(
    '"""Infrastructure layer: config, DI, repositories, and adapters."""\n',
)


INFRASTRUCTURE_REPOSITORIES_INIT_TEMPLATE = Template(
    '"""Infrastructure repositories and adapters."""\n',
)


PRESENTATION_INIT_TEMPLATE = Template(
    '"""Presentation layer: FastAPI, pybotx handlers, widgets, and FSM flows."""\n',
)


ARCHITECTURE_TEMPLATE = Template(
    """# Architecture

This scaffold uses a 4-layer clean architecture with `dependency-injector`.

## Layers

### `domain`

- pure business concepts
- entities, value objects, domain services, protocols
- repository and gateway contracts can live in `domain/ports/`
- no imports from `application`, `infrastructure`, `presentation`
- no framework imports such as `pybotx`, `fastapi`, `redis`, `dependency_injector`

### `application`

- use cases and orchestration
- coordinates domain logic and calls ports/repositories
- may import `domain`
- must not import `presentation` or concrete `infrastructure` implementations

### `infrastructure`

- DI container
- configuration
- repositories and external adapters
- concrete repository implementations live in `infrastructure/repositories/`
- may depend on `application` and `domain`
- must not import `presentation`

### `presentation`

- FastAPI app
- `pybotx` bot wiring
- commands, widgets, FSM flows
- handlers stay thin: parse -> call application service -> return response/widget

## Dependency Rule

Allowed direction:

`presentation -> application -> domain`

`infrastructure -> application -> domain`

`presentation` may depend on `infrastructure` only for composition roots like the DI container.

Forbidden direction:

- `domain -> application|infrastructure|presentation`
- `application -> infrastructure|presentation`
- `infrastructure -> presentation`

## DI

`dependency-injector` is the composition root. Concrete objects are assembled in:

- `$container_module`

Business code should not create its dependencies manually inside handlers.

## Where To Put New Code

### New command

1. `presentation/commands/<feature>.py`
2. `application/services/<feature>.py`
3. add or reuse domain contracts in `domain/` or `domain/ports/`
4. add infrastructure adapters/repositories in `infrastructure/`
5. register the service in `src/$package_name/container.py`

Or use:

```bash
uv run pybotx create command <name> --project-dir .
```

### New application service / use case

1. `application/services/<feature>.py`
2. optional contract in `domain/ports/`
3. optional adapter in `infrastructure/`
4. register the provider in `src/$package_name/container.py`

Or use:

```bash
uv run pybotx create service <name> --project-dir .
```

### New port

1. `domain/ports/<port>.py`
2. define the business-facing contract as `typing.Protocol`
3. implement the adapter later in `infrastructure/`

Or use:

```bash
uv run pybotx create port <name> --project-dir .
```

### New repository / port pair

1. `domain/ports/<repository>.py`
2. `infrastructure/repositories/<repository>.py`
3. register the provider in `src/$package_name/container.py`
4. inject the repository into application services through the generated provider

Or use:

```bash
uv run pybotx create repository <name> --project-dir .
```

If the port already exists:

```bash
uv run pybotx create repository <adapter-name> --project-dir . --port <port-name>
```

### New widget

1. `presentation/commands/<feature>.py`
2. `application/services/<feature>.py`
3. shared widget runtime helpers live in `presentation/widget_support.py`

Or use:

```bash
uv run pybotx create widget <name> --project-dir . --kind confirm
```

### New widget flow

1. `presentation/commands/<feature>.py`
2. `application/services/<feature>_widget.py`
3. `application/services/<feature>_result.py`
4. widget callback/result wiring stays in the generated command module

Or use:

```bash
uv run pybotx create widget-flow <name> --project-dir . --kind confirm
```

### New FSM flow

1. `presentation/fsm/<flow>.py`
2. starter command in `presentation/commands/<flow>.py`
3. flow state storage implementation belongs to `infrastructure/`

Or use:

```bash
uv run pybotx create fsm-flow <name> --project-dir .
```

## Practical Rules

- keep `pybotx` imports inside `presentation`
- keep `fastapi` imports inside `presentation`
- keep `pydantic-settings`, `redis`, `dependency_injector` inside `infrastructure`
- application services return plain values; they should not send messages directly
- widgets and FSM flows are presentation concerns

## Guardrails

The scaffold includes:

- `tests/test_architecture.py` to check layer import rules
- DI container in `src/$package_name/container.py`
- layered package layout from day one
- sample `GreetingProfileRepository` port with a DI-wired repository stub
"""
)


ARCHITECTURE_TEST_TEMPLATE = Template(
    """from __future__ import annotations

import ast
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parents[1] / "src" / "$package_name"
PACKAGE_PREFIX = "$package_name"

FORBIDDEN_LAYER_IMPORTS = {
    "domain": (
        f"{PACKAGE_PREFIX}.application",
        f"{PACKAGE_PREFIX}.infrastructure",
        f"{PACKAGE_PREFIX}.presentation",
    ),
    "application": (
        f"{PACKAGE_PREFIX}.infrastructure",
        f"{PACKAGE_PREFIX}.presentation",
    ),
    "infrastructure": (
        f"{PACKAGE_PREFIX}.presentation",
    ),
}

FORBIDDEN_EXTERNAL_IMPORTS = {
    "domain": (
        "pybotx",
        "fastapi",
        "redis",
        "dependency_injector",
        "pydantic_settings",
    ),
    "application": (
        "pybotx",
        "fastapi",
        "redis",
        "dependency_injector",
        "pydantic_settings",
    ),
}


def _iter_imported_modules(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    imported_modules: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported_modules.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.level != 0 or node.module is None:
                continue
            imported_modules.append(node.module)
    return imported_modules


def _iter_layer_files(layer: str) -> list[Path]:
    return sorted((PACKAGE_ROOT / layer).rglob("*.py"))


def test_layer_boundaries() -> None:
    for layer, forbidden_prefixes in FORBIDDEN_LAYER_IMPORTS.items():
        for path in _iter_layer_files(layer):
            imported_modules = _iter_imported_modules(path)
            for module_name in imported_modules:
                assert not module_name.startswith(forbidden_prefixes), (
                    f"{path} imports outer layer module {module_name}"
                )


def test_framework_imports_are_kept_out_of_inner_layers() -> None:
    for layer, forbidden_prefixes in FORBIDDEN_EXTERNAL_IMPORTS.items():
        for path in _iter_layer_files(layer):
            imported_modules = _iter_imported_modules(path)
            for module_name in imported_modules:
                assert not module_name.startswith(forbidden_prefixes), (
                    f"{path} imports framework module {module_name}"
                )
"""
)


CONFIG_TEMPLATE = Template(
    """from functools import lru_cache
from typing import Literal
from uuid import UUID

from pydantic import AnyHttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict
from pybotx import (
    BotAccountWithSecret,
    BotCommandProcessingConfig,
    DropOldestBotCommandOverloadStrategy,
    RejectNewBotCommandOverloadStrategy,
)


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    bot_id: UUID
    bot_cts_url: AnyHttpUrl
    bot_secret_key: str

    bot_display_name: str = "$display_name"

    bot_command_max_concurrency: int = 32
    bot_command_max_queue_size: int = 512
    bot_command_overload_action: Literal["reject_new", "drop_oldest"] = "reject_new"

    bot_enable_otel_tracing: bool = $enable_otel_tracing_python
    bot_otel_tracer_name: str = "$package_name.bot"

    def build_bot_account(self) -> BotAccountWithSecret:
        return BotAccountWithSecret(
            id=self.bot_id,
            cts_url=str(self.bot_cts_url),
            secret_key=self.bot_secret_key,
        )

    def build_command_processing_config(self) -> BotCommandProcessingConfig:
        overload_strategy = RejectNewBotCommandOverloadStrategy()
        if self.bot_command_overload_action == "drop_oldest":
            overload_strategy = DropOldestBotCommandOverloadStrategy()

        return BotCommandProcessingConfig(
            max_concurrency=self.bot_command_max_concurrency,
            max_queue_size=self.bot_command_max_queue_size,
            overload_strategy=overload_strategy,
        )


@lru_cache
def get_settings() -> AppSettings:
    return AppSettings()
"""
)


CONFIG_FSM_TEMPLATE = Template(
    """from functools import lru_cache
from typing import Literal
from uuid import UUID

from pydantic import AnyHttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict
from pybotx import (
    BotAccountWithSecret,
    BotCommandProcessingConfig,
    DropOldestBotCommandOverloadStrategy,
    RejectNewBotCommandOverloadStrategy,
)


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    bot_id: UUID
    bot_cts_url: AnyHttpUrl
    bot_secret_key: str

    bot_display_name: str = "$display_name"

    bot_command_max_concurrency: int = 32
    bot_command_max_queue_size: int = 512
    bot_command_overload_action: Literal["reject_new", "drop_oldest"] = "reject_new"

    bot_enable_otel_tracing: bool = $enable_otel_tracing_python
    bot_otel_tracer_name: str = "$package_name.bot"

    bot_fsm_redis_url: str = "redis://localhost:6379/0"
    bot_fsm_state_ttl_seconds: int = 900

    def build_bot_account(self) -> BotAccountWithSecret:
        return BotAccountWithSecret(
            id=self.bot_id,
            cts_url=str(self.bot_cts_url),
            secret_key=self.bot_secret_key,
        )

    def build_command_processing_config(self) -> BotCommandProcessingConfig:
        overload_strategy = RejectNewBotCommandOverloadStrategy()
        if self.bot_command_overload_action == "drop_oldest":
            overload_strategy = DropOldestBotCommandOverloadStrategy()

        return BotCommandProcessingConfig(
            max_concurrency=self.bot_command_max_concurrency,
            max_queue_size=self.bot_command_max_queue_size,
            overload_strategy=overload_strategy,
        )


@lru_cache
def get_settings() -> AppSettings:
    return AppSettings()
"""
)


CONTAINER_TEMPLATE = Template(
    """from dependency_injector import containers, providers
from prometheus_client import CollectorRegistry

from $bot_module import build_bot
from $config_module import get_settings
from $static_greeting_profile_repository_module import (
    StaticGreetingProfileRepository,
)
# pybotx-scaffold repository imports start
# pybotx-scaffold repository imports end
from $services_module_prefix.greeting import GreetingService
# pybotx-scaffold service imports start
# pybotx-scaffold service imports end


class ApplicationContainer(containers.DeclarativeContainer):
    settings = providers.Singleton(get_settings)
    prometheus_registry = providers.Singleton(CollectorRegistry)

    greeting_profile_repository = providers.Singleton(
        StaticGreetingProfileRepository,
        display_name=settings.provided.bot_display_name,
    )
    # pybotx-scaffold repository providers start
    # pybotx-scaffold repository providers end
    greeting_service = providers.Factory(
        GreetingService,
        greeting_profile_repository=greeting_profile_repository,
    )
    # pybotx-scaffold service providers start
    # pybotx-scaffold service providers end

    bot = providers.Singleton(
        build_bot,
        settings=settings,
        registry=prometheus_registry,
    )
"""
)


CONTAINER_FSM_TEMPLATE = Template(
    """from dependency_injector import containers, providers
from prometheus_client import CollectorRegistry
from redis.asyncio import from_url

from $bot_module import build_bot
from $config_module import get_settings
from $fsm_state_repo_module import RedisFSMStateRepo
from $static_greeting_profile_repository_module import (
    StaticGreetingProfileRepository,
)
# pybotx-scaffold repository imports start
# pybotx-scaffold repository imports end
from $services_module_prefix.auth import AuthService
from $services_module_prefix.greeting import GreetingService
# pybotx-scaffold service imports start
# pybotx-scaffold service imports end


class ApplicationContainer(containers.DeclarativeContainer):
    settings = providers.Singleton(get_settings)
    prometheus_registry = providers.Singleton(CollectorRegistry)

    greeting_profile_repository = providers.Singleton(
        StaticGreetingProfileRepository,
        display_name=settings.provided.bot_display_name,
    )
    # pybotx-scaffold repository providers start
    # pybotx-scaffold repository providers end
    greeting_service = providers.Factory(
        GreetingService,
        greeting_profile_repository=greeting_profile_repository,
    )
    auth_service = providers.Factory(
        AuthService,
        users={
            "demo@example.com": "password123",
            "admin@example.com": "admin123",
        },
    )

    fsm_redis_client = providers.Singleton(
        from_url,
        settings.provided.bot_fsm_redis_url,
        encoding="utf-8",
        decode_responses=True,
    )
    fsm_state_repo = providers.Singleton(
        RedisFSMStateRepo,
        redis=fsm_redis_client,
        default_expire_seconds=settings.provided.bot_fsm_state_ttl_seconds,
    )
    # pybotx-scaffold service providers start
    # pybotx-scaffold service providers end

    bot = providers.Singleton(
        build_bot,
        settings=settings,
        registry=prometheus_registry,
    )
"""
)


SERVICES_INIT_TEMPLATE = Template('"""Application services."""\n')


WIDGET_SUPPORT_TEMPLATE = Template(
    """from __future__ import annotations

from typing import TYPE_CHECKING, TypeVar, cast

from pybotx import Bot, IncomingMessage
from pybotx.widgets import (
    WidgetContext,
    WidgetFactory,
    WidgetRunnerConfig,
    build_production_widget_runner_preset,
)
from pybotx.widgets.base import Widget
from pybotx.widgets.runner import RunnerAfterHook, RunnerBeforeHook

if TYPE_CHECKING:
    from $container_module import ApplicationContainer

W = TypeVar("W", bound=Widget)


def get_container(bot: Bot) -> "ApplicationContainer":
    return cast("ApplicationContainer", bot.state.container)


def build_widget_factory(
    message: IncomingMessage,
    bot: Bot,
    *,
    command: str,
) -> WidgetFactory:
    return WidgetFactory(
        context=WidgetContext(
            message=message,
            bot=bot,
            command=command,
        ),
    )


def build_widget_runner_config(
    *,
    before: RunnerBeforeHook[W] | None = None,
    after: RunnerAfterHook[W] | None = None,
) -> WidgetRunnerConfig:
    return build_production_widget_runner_preset(
        before=before,
        after=after,
    ).as_config()
"""
)


GREETING_PROFILE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class GreetingProfile:
    display_name: str
    help_commands: tuple[str, ...] = (
        "/start - Show greeting",
        "/help - List available commands",
    )
"""
)


GREETING_PROFILE_REPOSITORY_TEMPLATE = Template(
    """from typing import Protocol

from $greeting_profile_module import GreetingProfile


class GreetingProfileRepository(Protocol):
    def get_profile(self) -> GreetingProfile:
        ...
"""
)


STATIC_GREETING_PROFILE_REPOSITORY_TEMPLATE = Template(
    """from dataclasses import dataclass

from $greeting_profile_module import GreetingProfile


@dataclass(frozen=True, slots=True)
class StaticGreetingProfileRepository:
    display_name: str
    help_commands: tuple[str, ...] = (
        "/start - Show greeting",
        "/help - List available commands",
    )

    def get_profile(self) -> GreetingProfile:
        return GreetingProfile(
            display_name=self.display_name,
            help_commands=self.help_commands,
        )
"""
)


REPOSITORY_PORT_TEMPLATE = Template(
    """from typing import Protocol


class $port_class_name(Protocol):
    \"\"\"Domain repository port for `$repository_slug`.

    Add domain-specific methods here, then implement them in the infrastructure
    adapter generated alongside this port.
    \"\"\"

    ...
"""
)


PORT_TEMPLATE = Template(
    """from typing import Protocol


class $port_class_name(Protocol):
    \"\"\"Domain port for `$port_slug`.

    Add business-facing methods here. Implement this contract in the
    infrastructure layer and inject it into application services through DI.
    \"\"\"

    ...
"""
)


REPOSITORY_IMPLEMENTATION_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(slots=True)
class $implementation_class_name:
    \"\"\"Infrastructure repository stub for `$repository_slug`.

    Replace this class with a concrete Redis/Postgres/HTTP implementation after
    defining the domain-specific contract in `domain/ports/` and wiring it into
    the `$port_class_name` port.
    \"\"\"

    ...
"""
)


GREETING_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass

from $greeting_profile_repository_module import GreetingProfileRepository


@dataclass(frozen=True, slots=True)
class GreetingService:
    greeting_profile_repository: GreetingProfileRepository

    def get_help_commands(self) -> tuple[str, ...]:
        return self.greeting_profile_repository.get_profile().help_commands

    def build_start_message(self) -> str:
        profile = self.greeting_profile_repository.get_profile()
        return (
            f"Hello from {profile.display_name}.\\n\\n"
            "Use /help to see available commands."
        )

    def build_help_message(self) -> str:
        return "\\n".join(self.get_help_commands())
"""
)


AUTH_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class AuthService:
    users: dict[str, str] = field(default_factory=dict)

    def is_known_email(self, email: str) -> bool:
        return email in self.users

    def is_valid_password(self, email: str, password: str) -> bool:
        return self.users.get(email) == password
"""
)


COMMANDS_INIT_TEMPLATE = Template(
    """from $commands_module_prefix.common import collector as common_collector
# pybotx-scaffold command imports start
# pybotx-scaffold command imports end

collectors = [
    common_collector,
    # pybotx-scaffold command collectors start
    # pybotx-scaffold command collectors end
]
"""
)


COMMANDS_INIT_FSM_TEMPLATE = Template(
    """from $commands_module_prefix.common import collector as common_collector
from $fsm_module_prefix.login import fsm as login_fsm
# pybotx-scaffold command imports start
# pybotx-scaffold command imports end

collectors = [
    common_collector,
    login_fsm,
    # pybotx-scaffold command collectors start
    # pybotx-scaffold command collectors end
]
"""
)


COMMON_COMMANDS_TEMPLATE = Template(
    """from typing import TYPE_CHECKING, cast

from pybotx import Bot, HandlerCollector, IncomingMessage

if TYPE_CHECKING:
    from $container_module import ApplicationContainer


collector = HandlerCollector()


def _get_container(bot: Bot) -> "ApplicationContainer":
    return cast("ApplicationContainer", bot.state.container)


@collector.command("/start", description="Show greeting")
async def start_handler(_: IncomingMessage, bot: Bot) -> None:
    greeting_service = _get_container(bot).greeting_service()
    await bot.answer_message(greeting_service.build_start_message())


@collector.command("/help", description="List available commands")
async def help_handler(_: IncomingMessage, bot: Bot) -> None:
    greeting_service = _get_container(bot).greeting_service()
    await bot.answer_message(greeting_service.build_help_message())
"""
)


COMMON_COMMANDS_FSM_TEMPLATE = Template(
    """from typing import TYPE_CHECKING, cast

from pybotx import Bot, HandlerCollector, IncomingMessage

from $fsm_module_prefix.login import LoginStates

if TYPE_CHECKING:
    from $container_module import ApplicationContainer


collector = HandlerCollector()


def _get_container(bot: Bot) -> "ApplicationContainer":
    return cast("ApplicationContainer", bot.state.container)


@collector.command("/start", description="Show greeting")
async def start_handler(_: IncomingMessage, bot: Bot) -> None:
    greeting_service = _get_container(bot).greeting_service()
    await bot.answer_message(greeting_service.build_start_message())


@collector.command("/help", description="List available commands")
async def help_handler(_: IncomingMessage, bot: Bot) -> None:
    greeting_service = _get_container(bot).greeting_service()
    await bot.answer_message(
        "\\n".join(
            [
                *greeting_service.get_help_commands(),
                "/login - Start demo FSM login flow",
                "/cancel - Drop the current FSM state",
            ],
        ),
    )


@collector.command("/login", description="Start demo FSM login flow")
async def login_handler(message: IncomingMessage, bot: Bot) -> None:
    await message.state.fsm.change_state(LoginStates.ENTER_EMAIL)
    await bot.answer_message("Enter your email.")


@collector.command("/cancel", description="Drop active FSM state")
async def cancel_handler(message: IncomingMessage, bot: Bot) -> None:
    state = await message.state.fsm.get_state()
    if state is None:
        await bot.answer_message("No active login flow.")
        return

    await message.state.fsm.drop_state()
    await bot.answer_message("Login flow cancelled.")
"""
)


BOT_TEMPLATE = Template(
    """from prometheus_client import CollectorRegistry
from pybotx import (
    Bot,
    build_production_bot_preset,
    build_production_observability_preset,
)

from $commands_module_prefix import collectors
from $config_module import AppSettings


def build_bot(*, settings: AppSettings, registry: CollectorRegistry) -> Bot:
    production_preset = build_production_bot_preset(
        observability_preset=build_production_observability_preset(
            registry=registry,
            enable_open_telemetry_tracing=settings.bot_enable_otel_tracing,
            tracer_name=settings.bot_otel_tracer_name,
        ),
    )
    bot_kwargs = production_preset.as_bot_kwargs()
    return Bot(
        collectors=collectors,
        bot_accounts=[settings.build_bot_account()],
        command_processing_config=settings.build_command_processing_config(),
        **bot_kwargs,
    )
"""
)


BOT_FSM_TEMPLATE = Template(
    """from prometheus_client import CollectorRegistry
from pybotx import (
    Bot,
    build_production_bot_preset,
    build_production_observability_preset,
)
from pybotx_fsm import FSMMiddleware

from $commands_module_prefix import collectors
from $config_module import AppSettings
from $fsm_module_prefix.login import fsm as login_fsm
# pybotx-scaffold fsm imports start
# pybotx-scaffold fsm imports end


def build_bot(*, settings: AppSettings, registry: CollectorRegistry) -> Bot:
    production_preset = build_production_bot_preset(
        observability_preset=build_production_observability_preset(
            registry=registry,
            enable_open_telemetry_tracing=settings.bot_enable_otel_tracing,
            tracer_name=settings.bot_otel_tracer_name,
        ),
    )
    bot_kwargs = production_preset.as_bot_kwargs()
    return Bot(
        collectors=collectors,
        bot_accounts=[settings.build_bot_account()],
        command_processing_config=settings.build_command_processing_config(),
        middlewares=[
            FSMMiddleware(
                [
                    login_fsm,
                    # pybotx-scaffold fsm collectors start
                    # pybotx-scaffold fsm collectors end
                ],
                state_repo_key="fsm_state_repo",
            ),
        ],
        **bot_kwargs,
    )
"""
)


PRESENTATION_API_TEMPLATE = Template(
    """from fastapi import FastAPI
from pybotx import FastAPIBotAppConfig, create_fastapi_bot_app

from $container_module import ApplicationContainer


def create_app() -> FastAPI:
    container = ApplicationContainer()
    settings = container.settings()
    bot = container.bot()
    bot.state.container = container
    return create_fastapi_bot_app(
        bot=bot,
        title=settings.bot_display_name,
        openapi_url=None,
        docs_url=None,
        redoc_url=None,
        config=FastAPIBotAppConfig(
            metrics_path="/metrics",
        ),
        metrics_registry=container.prometheus_registry(),
        app_state={"container": container},
    )


app = create_app()
"""
)


MAIN_TEMPLATE = Template(
    """from fastapi import FastAPI

from $api_module import create_app


app: FastAPI = create_app()
"""
)


MAIN_FSM_TEMPLATE = Template(
    """from fastapi import FastAPI

from $api_module import create_app


app: FastAPI = create_app()
"""
)


PRESENTATION_API_FSM_TEMPLATE = Template(
    """from fastapi import FastAPI
from pybotx import (
    FastAPIBotAppConfig,
    ReadinessCheck,
    ReadinessCheckResult,
    create_fastapi_bot_app,
)

from $container_module import ApplicationContainer


async def _check_fsm_redis(container: ApplicationContainer) -> ReadinessCheckResult:
    redis = container.fsm_redis_client()
    await redis.ping()
    return ReadinessCheckResult(status="ok")


def create_app() -> FastAPI:
    container = ApplicationContainer()
    settings = container.settings()
    bot = container.bot()
    bot.state.container = container
    bot.state.fsm_state_repo = container.fsm_state_repo()

    app = create_fastapi_bot_app(
        bot=bot,
        title=settings.bot_display_name,
        openapi_url=None,
        docs_url=None,
        redoc_url=None,
        config=FastAPIBotAppConfig(
            metrics_path="/metrics",
        ),
        metrics_registry=container.prometheus_registry(),
        app_state={"container": container},
    )
    app.state.healthcheck.add_readiness_check(
        ReadinessCheck(
            name="fsm_redis",
            check=lambda: _check_fsm_redis(container),
            critical=True,
            timeout_seconds=0.5,
        ),
    )

    async def shutdown_redis() -> None:
        await container.fsm_redis_client().aclose()

    app.add_event_handler("shutdown", shutdown_redis)
    return app
"""
)


FSM_INIT_TEMPLATE = Template('"""FSM flows."""\n')


FSM_LOGIN_TEMPLATE = Template(
    """from enum import Enum, auto
from typing import TYPE_CHECKING, cast

from pybotx import Bot, IncomingMessage
from pybotx_fsm import FSMCollector

if TYPE_CHECKING:
    from $container_module import ApplicationContainer


class LoginStates(Enum):
    ENTER_EMAIL = auto()
    ENTER_PASSWORD = auto()


fsm = FSMCollector(LoginStates)


def _get_container(bot: Bot) -> "ApplicationContainer":
    return cast("ApplicationContainer", bot.state.container)


@fsm.on(LoginStates.ENTER_EMAIL)
async def enter_email(message: IncomingMessage, bot: Bot) -> None:
    auth_service = _get_container(bot).auth_service()
    email = message.body.strip()

    if not auth_service.is_known_email(email):
        await bot.answer_message("Unknown email, try again.")
        return

    await message.state.fsm.change_state(LoginStates.ENTER_PASSWORD, email=email)
    await bot.answer_message("Enter your password.")


@fsm.on(LoginStates.ENTER_PASSWORD)
async def enter_password(message: IncomingMessage, bot: Bot) -> None:
    auth_service = _get_container(bot).auth_service()
    email = message.state.fsm_storage.email
    password = message.body

    if not auth_service.is_valid_password(email, password):
        await bot.answer_message("Wrong password, try again.")
        return

    await message.state.fsm.drop_state()
    await bot.answer_message(f"Logged in as {email}.")
"""
)


FSM_STATE_REPO_TEMPLATE = Template(
    """from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import importlib
import json
from types import SimpleNamespace
from typing import Any

from pybotx_fsm.fsm import FSMStateData
from redis.asyncio import Redis


@dataclass(frozen=True, slots=True)
class RedisFSMStateRepo:
    redis: Redis
    default_expire_seconds: int = 900
    key_prefix: str = "pybotx:fsm"

    def __post_init__(self) -> None:
        if self.default_expire_seconds <= 0:
            raise ValueError("FSM state TTL should be greater than 0")
        if not self.key_prefix:
            raise ValueError("FSM state key prefix should not be empty")

    async def get(self, key: Any, default: Any = None) -> Any:
        payload = await self.redis.get(self._build_redis_key(key))
        if payload is None:
            return default

        parsed_payload = json.loads(payload)
        enum_cls = self._load_enum_class(
            module_name=parsed_payload["state_module"],
            qualname=parsed_payload["state_qualname"],
        )
        state = enum_cls[parsed_payload["state_name"]]
        storage = SimpleNamespace(**parsed_payload["storage"])
        return FSMStateData(state=state, storage=storage)

    async def set(
        self,
        key: Any,
        value: Any,
        expire: int | None = None,
    ) -> None:
        if not isinstance(value, FSMStateData):
            raise TypeError("RedisFSMStateRepo expects FSMStateData values")
        if not isinstance(value.state, Enum):
            raise TypeError("FSM state should be an Enum member")

        storage = vars(value.storage)
        payload = json.dumps(
            {
                "state_module": value.state.__class__.__module__,
                "state_qualname": value.state.__class__.__qualname__,
                "state_name": value.state.name,
                "storage": storage,
            },
            ensure_ascii=True,
            sort_keys=True,
        )
        await self.redis.set(
            self._build_redis_key(key),
            payload,
            ex=expire or self.default_expire_seconds,
        )

    async def delete(self, key: Any) -> None:
        await self.redis.delete(self._build_redis_key(key))

    def _build_redis_key(self, key: Any) -> str:
        return f"{self.key_prefix}:{key}"

    def _load_enum_class(self, *, module_name: str, qualname: str) -> type[Enum]:
        module = importlib.import_module(module_name)
        target: Any = module
        for part in qualname.split("."):
            target = getattr(target, part)

        if not isinstance(target, type) or not issubclass(target, Enum):
            raise TypeError(
                f"Stored FSM state class `{module_name}:{qualname}` is not an Enum",
            )

        return target
"""
)


TESTS_CONFTEST_TEMPLATE = Template(
    """from collections.abc import Callable
from types import SimpleNamespace
from unittest.mock import AsyncMock
from uuid import UUID, uuid4

from dependency_injector import providers
import pytest
from pybotx import (
    Bot,
    BotAccount,
    BotAccountWithSecret,
    Chat,
    ChatTypes,
    IncomingMessage,
    UserDevice,
    UserSender,
)

from $commands_module_prefix import collectors
from $container_module import ApplicationContainer


@pytest.fixture
def bot_account() -> BotAccountWithSecret:
    return BotAccountWithSecret(
        id=UUID("123e4567-e89b-12d3-a456-426655440000"),
        cts_url="https://cts.example.com",
        secret_key="test-secret",
    )


@pytest.fixture
def container() -> ApplicationContainer:
    built_container = ApplicationContainer()
    built_container.settings.override(
        providers.Object(SimpleNamespace(bot_display_name="Test Bot")),
    )
    return built_container


@pytest.fixture
def bot(
    bot_account: BotAccountWithSecret,
    container: ApplicationContainer,
) -> Bot:
    built_bot = Bot(
        collectors=collectors,
        bot_accounts=[bot_account],
    )
    built_bot.answer_message = AsyncMock(return_value=uuid4())  # type: ignore[method-assign]
    built_bot.send = AsyncMock(return_value=uuid4())  # type: ignore[method-assign]
    built_bot.edit_message = AsyncMock()  # type: ignore[method-assign]
    built_bot.state.container = container
    return built_bot


@pytest.fixture
def incoming_message_factory(
    bot_account: BotAccountWithSecret,
) -> Callable[..., IncomingMessage]:
    def factory(*, body: str = "/start") -> IncomingMessage:
        return IncomingMessage(
            bot=BotAccount(id=bot_account.id, host=bot_account.host),
            sync_id=uuid4(),
            source_sync_id=None,
            body=body,
            data={},
            metadata={},
            sender=UserSender(
                huid=UUID("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                udid=None,
                ad_login=None,
                ad_domain=None,
                username="Test User",
                is_chat_admin=True,
                is_chat_creator=True,
                device=UserDevice(
                    manufacturer=None,
                    device_name=None,
                    os=None,
                    pushes=None,
                    timezone=None,
                    permissions=None,
                    platform=None,
                    platform_package_id=None,
                    app_version=None,
                    locale=None,
                ),
            ),
            chat=Chat(
                id=uuid4(),
                type=ChatTypes.PERSONAL_CHAT,
            ),
            raw_command=None,
        )

    return factory
"""
)


TESTS_CONFTEST_FSM_TEMPLATE = Template(
    """from collections.abc import Callable
from types import SimpleNamespace
from unittest.mock import AsyncMock
from uuid import UUID, uuid4

from dependency_injector import providers
import pytest
from pybotx import (
    Bot,
    BotAccount,
    BotAccountWithSecret,
    Chat,
    ChatTypes,
    IncomingMessage,
    UserDevice,
    UserSender,
)

from pybotx_fsm import FSMMiddleware

from $commands_module_prefix import collectors
from $container_module import ApplicationContainer
from $fsm_module_prefix.login import fsm as login_fsm
# pybotx-scaffold fsm imports start
# pybotx-scaffold fsm imports end


class InMemoryFSMStateRepo:
    def __init__(self) -> None:
        self._storage: dict[object, object] = {}

    async def get(self, key: object, default: object = None) -> object:
        return self._storage.get(key, default)

    async def set(self, key: object, value: object, expire: int | None = None) -> None:
        self._storage[key] = value

    async def delete(self, key: object) -> None:
        self._storage.pop(key, None)


@pytest.fixture
def bot_account() -> BotAccountWithSecret:
    return BotAccountWithSecret(
        id=UUID("123e4567-e89b-12d3-a456-426655440000"),
        cts_url="https://cts.example.com",
        secret_key="test-secret",
    )


@pytest.fixture
def container() -> ApplicationContainer:
    built_container = ApplicationContainer()
    built_container.settings.override(
        providers.Object(
            SimpleNamespace(
                bot_display_name="Test Bot",
                bot_fsm_redis_url="redis://localhost:6379/0",
                bot_fsm_state_ttl_seconds=900,
            ),
        ),
    )
    return built_container


@pytest.fixture
def bot(
    bot_account: BotAccountWithSecret,
    container: ApplicationContainer,
) -> Bot:
    built_bot = Bot(
        collectors=collectors,
        bot_accounts=[bot_account],
        middlewares=[
            FSMMiddleware(
                [
                    login_fsm,
                    # pybotx-scaffold fsm collectors start
                    # pybotx-scaffold fsm collectors end
                ],
                state_repo_key="fsm_state_repo",
            ),
        ],
    )
    built_bot.answer_message = AsyncMock(return_value=uuid4())  # type: ignore[method-assign]
    built_bot.send = AsyncMock(return_value=uuid4())  # type: ignore[method-assign]
    built_bot.edit_message = AsyncMock()  # type: ignore[method-assign]
    built_bot.state.container = container
    built_bot.state.fsm_state_repo = InMemoryFSMStateRepo()
    return built_bot


@pytest.fixture
def incoming_message_factory(
    bot_account: BotAccountWithSecret,
) -> Callable[..., IncomingMessage]:
    stable_chat_id = UUID("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
    stable_user_huid = UUID("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")

    def factory(*, body: str = "/start") -> IncomingMessage:
        return IncomingMessage(
            bot=BotAccount(id=bot_account.id, host=bot_account.host),
            sync_id=uuid4(),
            source_sync_id=None,
            body=body,
            data={},
            metadata={},
            sender=UserSender(
                huid=stable_user_huid,
                udid=None,
                ad_login=None,
                ad_domain=None,
                username="Test User",
                is_chat_admin=True,
                is_chat_creator=True,
                device=UserDevice(
                    manufacturer=None,
                    device_name=None,
                    os=None,
                    pushes=None,
                    timezone=None,
                    permissions=None,
                    platform=None,
                    platform_package_id=None,
                    app_version=None,
                    locale=None,
                ),
            ),
            chat=Chat(
                id=stable_chat_id,
                type=ChatTypes.PERSONAL_CHAT,
            ),
            raw_command=None,
        )

    return factory
"""
)


TEST_START_COMMAND_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage


async def test_start_handler(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body="/start")

    await bot.async_execute_bot_command(message)

    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        "Hello from Test Bot.\\n\\nUse /help to see available commands.",
    )


async def test_help_handler(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body="/help")

    await bot.async_execute_bot_command(message)

    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        "/start - Show greeting\\n/help - List available commands",
    )
"""
)


TEST_START_COMMAND_FSM_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage


async def test_start_handler(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body="/start"))

    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        "Hello from Test Bot.\\n\\nUse /help to see available commands.",
    )


async def test_login_fsm_flow(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body="/login"))
    bot.answer_message.assert_awaited_once_with("Enter your email.")  # type: ignore[attr-defined]

    bot.answer_message.reset_mock()  # type: ignore[attr-defined]
    await bot.async_execute_bot_command(
        incoming_message_factory(body="demo@example.com"),
    )
    bot.answer_message.assert_awaited_once_with("Enter your password.")  # type: ignore[attr-defined]

    bot.answer_message.reset_mock()  # type: ignore[attr-defined]
    await bot.async_execute_bot_command(incoming_message_factory(body="password123"))
    bot.answer_message.assert_awaited_once_with("Logged in as demo@example.com.")  # type: ignore[attr-defined]
"""
)


COMMAND_MODULE_TEMPLATE = Template(
    """from typing import TYPE_CHECKING, cast

from pybotx import Bot, HandlerCollector, IncomingMessage

if TYPE_CHECKING:
    from $container_module import ApplicationContainer


collector = HandlerCollector()


def _get_container(bot: Bot) -> "ApplicationContainer":
    return cast("ApplicationContainer", bot.state.container)


@collector.command($command_literal, description=$description_literal)
async def $handler_name(_: IncomingMessage, bot: Bot) -> None:
    command_service = _get_container(bot).$service_provider_name()
    await bot.answer_message(command_service.handle())
"""
)


SERVICE_MODULE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def handle(self) -> str:
        return $response_text_literal
"""
)


COMMAND_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage


async def test_${module_name}_handler(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)

    await bot.async_execute_bot_command(message)

    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        $response_text_literal,
    )
"""
)


APPLICATION_SERVICE_TEST_TEMPLATE = Template(
    """from $services_module_prefix.$module_name import $service_class_name


def test_${module_name}_service() -> None:
    service = $service_class_name()

    assert service.handle() == $response_text_literal
"""
)


REPOSITORY_TEST_TEMPLATE = Template(
    """from $container_module import ApplicationContainer
from $repository_module import $implementation_class_name


def test_${module_name}_repository_provider() -> None:
    container = ApplicationContainer()

    repository = container.$repository_provider_name()

    assert isinstance(repository, $implementation_class_name)
"""
)


WIDGET_CONFIRM_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import ConfirmWidget, on_action, widget_command
from pybotx.widgets.confirm import CANCEL_ACTION, CONFIRM_ACTION

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_action(
            lambda widget: ConfirmWidget.get_action(widget.message),
            {
                CONFIRM_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$service_provider_name()
                    .build_action_result(CONFIRM_ACTION)
                ),
                CANCEL_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$service_provider_name()
                    .build_action_result(CANCEL_ACTION)
                ),
            },
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> ConfirmWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.confirm(label=widget_service.build_label())
"""
)


WIDGET_CONFIRM_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_action_result(self, action: str) -> str:
        if action == "confirm":
            return $primary_result_literal
        if action == "cancel":
            return $secondary_result_literal

        return f"Unhandled widget action: {action}"
"""
)


WIDGET_CONFIRM_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.confirm import CONFIRM_ACTION, CONFIRM_ACTION_KEY


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_action(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {CONFIRM_ACTION_KEY: CONFIRM_ACTION}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_APPROVAL_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import ApprovalWidget, on_action, widget_command
from pybotx.widgets.approval import APPROVE_ACTION, COMMENT_ACTION, REJECT_ACTION

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_action(
            lambda widget: ApprovalWidget.get_action(widget.message),
            {
                APPROVE_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$service_provider_name()
                    .build_action_result(APPROVE_ACTION)
                ),
                REJECT_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$service_provider_name()
                    .build_action_result(REJECT_ACTION)
                ),
                COMMENT_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$service_provider_name()
                    .build_action_result(COMMENT_ACTION)
                ),
            },
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> ApprovalWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.approval(label=widget_service.build_label())
"""
)


WIDGET_APPROVAL_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_action_result(self, action: str) -> str:
        if action == "approve":
            return $primary_result_literal
        if action == "reject":
            return $secondary_result_literal
        if action == "comment":
            return $tertiary_result_literal

        return f"Unhandled widget action: {action}"
"""
)


WIDGET_APPROVAL_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.approval import APPROVAL_ACTION_KEY, APPROVE_ACTION


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_action(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {APPROVAL_ACTION_KEY: APPROVE_ACTION}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import SelectWidget, widget_command, on_data_key
from pybotx.widgets.select import SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(
            SELECT_VALUE_KEY,
            lambda widget: (
                get_container(widget.bot)
                .$service_provider_name()
                .build_selection_result(SelectWidget.get_value(widget.message))
            ),
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> SelectWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
    )
"""
)


WIDGET_SELECT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_options(self) -> list[str]:
        return [
            "dev",
            "staging",
            "prod",
        ]

    def build_selection_result(self, value: str) -> str:
        return f"Selected value: {value}"
"""
)


WIDGET_SELECT_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.select import SELECT_VALUE_KEY


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_selection(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {SELECT_VALUE_KEY: "prod"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == "Selected value: prod"  # type: ignore[attr-defined]
"""
)


WIDGET_SEARCH_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import SearchSelectWidget, on_data_key, widget_command
from pybotx.widgets.select import SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(
            SELECT_VALUE_KEY,
            lambda widget: (
                get_container(widget.bot)
                .$service_provider_name()
                .build_selection_result(SearchSelectWidget.get_value(widget.message))
            ),
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> SearchSelectWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.search_select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
    )
"""
)


WIDGET_SEARCH_SELECT_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.select import SELECT_VALUE_KEY


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_selection(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {SELECT_VALUE_KEY: "prod"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == "Selected value: prod"  # type: ignore[attr-defined]
"""
)


WIDGET_MULTI_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import MultiSelectWidget, RunnerHookResult, on_data_key, widget_command
from pybotx.widgets.multi_select import MULTI_SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


def _resolve_multi_select_result(widget: MultiSelectWidget) -> RunnerHookResult | None:
    widget_service = get_container(widget.bot).$service_provider_name()
    selected_values = widget.selected_values
    if not widget_service.is_selection_complete(selected_values):
        return None

    return RunnerHookResult(
        result=widget_service.build_selection_result(selected_values),
        should_display=False,
    )


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(MULTI_SELECT_VALUE_KEY, _resolve_multi_select_result),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> MultiSelectWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.multi_select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
        max_selected=widget_service.max_selected(),
    )
"""
)


WIDGET_MULTI_SELECT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_options(self) -> list[str]:
        return [
            "dev",
            "staging",
            "prod",
        ]

    def max_selected(self) -> int:
        return 2

    def is_selection_complete(self, values: list[str]) -> bool:
        return len(values) >= self.max_selected()

    def build_selection_result(self, values: list[str]) -> str:
        return f"Selected values: {', '.join(values)}"
"""
)


WIDGET_MULTI_SELECT_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.multi_select import MULTI_SELECTED_VALUES_KEY, MULTI_SELECT_VALUE_KEY


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_completed_selection(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.metadata = {
        MULTI_SELECTED_VALUES_KEY: ["dev"],
    }
    message.data = {MULTI_SELECT_VALUE_KEY: "prod"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_DATE_RANGE_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import DateRangeWidget, RunnerHookResult, on_data_key, widget_command
from pybotx.widgets.date_range import DATE_RANGE_SELECTED_DATE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


def _resolve_date_range_result(widget: DateRangeWidget) -> RunnerHookResult | None:
    if widget.start is None or widget.end is None:
        return None

    widget_service = get_container(widget.bot).$service_provider_name()
    return RunnerHookResult(
        result=widget_service.build_selection_result(widget.start, widget.end),
        should_display=False,
    )


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(DATE_RANGE_SELECTED_DATE_KEY, _resolve_date_range_result),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> DateRangeWidget:
    widget_service = get_container(bot).$service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.date_range(label=widget_service.build_label())
"""
)


WIDGET_DATE_RANGE_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True, slots=True)
class $service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_selection_result(self, start_date: date, end_date: date) -> str:
        return f"Selected period: {start_date.isoformat()} - {end_date.isoformat()}"
"""
)


WIDGET_DATE_RANGE_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.date_range import (
    DATE_RANGE_CURSOR_KEY,
    DATE_RANGE_SELECTED_DATE_KEY,
    DATE_RANGE_START_KEY,
)


async def test_${module_name}_widget_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $display_body_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_handles_completed_range(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.metadata = {
        DATE_RANGE_START_KEY: "2026-03-01",
        DATE_RANGE_CURSOR_KEY: "end",
    }
    message.data = {DATE_RANGE_SELECTED_DATE_KEY: "2026-03-08"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_FLOW_LABEL_WIDGET_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $widget_service_class_name:
    def build_label(self) -> str:
        return $label_literal
"""
)


WIDGET_FLOW_OPTIONS_WIDGET_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $widget_service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_options(self) -> list[str]:
        return [
            "dev",
            "staging",
            "prod",
        ]
"""
)


WIDGET_FLOW_MULTI_SELECT_WIDGET_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $widget_service_class_name:
    def build_label(self) -> str:
        return $label_literal

    def build_options(self) -> list[str]:
        return [
            "dev",
            "staging",
            "prod",
        ]

    def max_selected(self) -> int:
        return 2
"""
)


WIDGET_FLOW_CONFIRM_RESULT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $result_service_class_name:
    def handle_action(self, action: str) -> str:
        if action == "confirm":
            return $primary_result_literal
        if action == "cancel":
            return $secondary_result_literal

        return f"Unhandled widget action: {action}"
"""
)


WIDGET_FLOW_APPROVAL_RESULT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $result_service_class_name:
    def handle_action(self, action: str) -> str:
        if action == "approve":
            return $primary_result_literal
        if action == "reject":
            return $secondary_result_literal
        if action == "comment":
            return $tertiary_result_literal

        return f"Unhandled widget action: {action}"
"""
)


WIDGET_FLOW_SELECTION_RESULT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $result_service_class_name:
    def handle_selection(self, value: str) -> str:
        return f"Selected value: {value}"
"""
)


WIDGET_FLOW_MULTI_SELECTION_RESULT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class $result_service_class_name:
    def handle_selection(self, values: list[str]) -> str:
        return f"Selected values: {', '.join(values)}"
"""
)


WIDGET_FLOW_DATE_RANGE_RESULT_SERVICE_TEMPLATE = Template(
    """from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True, slots=True)
class $result_service_class_name:
    def handle_selection(self, start_date: date, end_date: date) -> str:
        return f"Selected period: {start_date.isoformat()} - {end_date.isoformat()}"
"""
)


WIDGET_FLOW_CONFIRM_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import ConfirmWidget, on_action, widget_command
from pybotx.widgets.confirm import CANCEL_ACTION, CONFIRM_ACTION

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_action(
            lambda widget: ConfirmWidget.get_action(widget.message),
            {
                CONFIRM_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$result_service_provider_name()
                    .handle_action(CONFIRM_ACTION)
                ),
                CANCEL_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$result_service_provider_name()
                    .handle_action(CANCEL_ACTION)
                ),
            },
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> ConfirmWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.confirm(label=widget_service.build_label())
"""
)


WIDGET_FLOW_APPROVAL_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import ApprovalWidget, on_action, widget_command
from pybotx.widgets.approval import APPROVE_ACTION, COMMENT_ACTION, REJECT_ACTION

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_action(
            lambda widget: ApprovalWidget.get_action(widget.message),
            {
                APPROVE_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$result_service_provider_name()
                    .handle_action(APPROVE_ACTION)
                ),
                REJECT_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$result_service_provider_name()
                    .handle_action(REJECT_ACTION)
                ),
                COMMENT_ACTION: lambda widget: (
                    get_container(widget.bot)
                    .$result_service_provider_name()
                    .handle_action(COMMENT_ACTION)
                ),
            },
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> ApprovalWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.approval(label=widget_service.build_label())
"""
)


WIDGET_FLOW_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import SelectWidget, on_data_key, widget_command
from pybotx.widgets.select import SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(
            SELECT_VALUE_KEY,
            lambda widget: (
                get_container(widget.bot)
                .$result_service_provider_name()
                .handle_selection(SelectWidget.get_value(widget.message))
            ),
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> SelectWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
    )
"""
)


WIDGET_FLOW_SEARCH_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import SearchSelectWidget, on_data_key, widget_command
from pybotx.widgets.select import SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(
            SELECT_VALUE_KEY,
            lambda widget: (
                get_container(widget.bot)
                .$result_service_provider_name()
                .handle_selection(SearchSelectWidget.get_value(widget.message))
            ),
        ),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> SearchSelectWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.search_select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
    )
"""
)


WIDGET_FLOW_MULTI_SELECT_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import MultiSelectWidget, RunnerHookResult, on_data_key, widget_command
from pybotx.widgets.multi_select import MULTI_SELECT_VALUE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


def _resolve_multi_select_result(widget: MultiSelectWidget) -> RunnerHookResult | None:
    container = get_container(widget.bot)
    widget_service = container.$widget_service_provider_name()
    selected_values = widget.selected_values
    if len(selected_values) < widget_service.max_selected():
        return None

    return RunnerHookResult(
        result=container.$result_service_provider_name().handle_selection(selected_values),
        should_display=False,
    )


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(MULTI_SELECT_VALUE_KEY, _resolve_multi_select_result),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> MultiSelectWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.multi_select(
        label=widget_service.build_label(),
        options=widget_service.build_options(),
        max_selected=widget_service.max_selected(),
    )
"""
)


WIDGET_FLOW_DATE_RANGE_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage
from pybotx.widgets import DateRangeWidget, RunnerHookResult, on_data_key, widget_command
from pybotx.widgets.date_range import DATE_RANGE_SELECTED_DATE_KEY

from $widget_support_module import (
    build_widget_factory,
    build_widget_runner_config,
    get_container,
)


collector = HandlerCollector()
COMMAND_NAME = $command_literal


def _resolve_date_range_result(widget: DateRangeWidget) -> RunnerHookResult | None:
    if widget.start is None or widget.end is None:
        return None

    return RunnerHookResult(
        result=(
            get_container(widget.bot)
            .$result_service_provider_name()
            .handle_selection(widget.start, widget.end)
        ),
        should_display=False,
    )


@collector.command(COMMAND_NAME, description=$description_literal)
@widget_command(
    config=build_widget_runner_config(
        before=on_data_key(DATE_RANGE_SELECTED_DATE_KEY, _resolve_date_range_result),
    ),
)
async def $handler_name(message: IncomingMessage, bot: Bot) -> DateRangeWidget:
    widget_service = get_container(bot).$widget_service_provider_name()
    widgets = build_widget_factory(message, bot, command=COMMAND_NAME)
    return widgets.date_range(label=widget_service.build_label())
"""
)


WIDGET_FLOW_CONFIRM_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.confirm import CONFIRM_ACTION, CONFIRM_ACTION_KEY


async def test_${module_name}_widget_flow_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_flow_handles_action(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {CONFIRM_ACTION_KEY: CONFIRM_ACTION}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_FLOW_APPROVAL_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.approval import APPROVAL_ACTION_KEY, APPROVE_ACTION


async def test_${module_name}_widget_flow_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_flow_handles_action(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {APPROVAL_ACTION_KEY: APPROVE_ACTION}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $primary_result_literal  # type: ignore[attr-defined]
"""
)


WIDGET_FLOW_SELECT_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.select import SELECT_VALUE_KEY


async def test_${module_name}_widget_flow_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_flow_handles_selection(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.data = {SELECT_VALUE_KEY: "prod"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == "Selected value: prod"  # type: ignore[attr-defined]
"""
)


WIDGET_FLOW_MULTI_SELECT_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.multi_select import MULTI_SELECTED_VALUES_KEY, MULTI_SELECT_VALUE_KEY


async def test_${module_name}_widget_flow_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $label_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_flow_handles_completed_selection(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.metadata = {
        MULTI_SELECTED_VALUES_KEY: ["dev"],
    }
    message.data = {MULTI_SELECT_VALUE_KEY: "prod"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == "Selected values: dev, prod"  # type: ignore[attr-defined]
"""
)


WIDGET_FLOW_DATE_RANGE_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage
from pybotx.widgets.date_range import (
    DATE_RANGE_CURSOR_KEY,
    DATE_RANGE_SELECTED_DATE_KEY,
    DATE_RANGE_START_KEY,
)


async def test_${module_name}_widget_flow_displays(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == $display_body_literal  # type: ignore[attr-defined]


async def test_${module_name}_widget_flow_handles_completed_range(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    message = incoming_message_factory(body=$command_literal)
    message.metadata = {
        DATE_RANGE_START_KEY: "2026-03-01",
        DATE_RANGE_CURSOR_KEY: "end",
    }
    message.data = {DATE_RANGE_SELECTED_DATE_KEY: "2026-03-08"}

    await bot.async_execute_bot_command(message)

    bot.send.assert_awaited_once()  # type: ignore[attr-defined]
    assert bot.send.await_args.kwargs["message"].body == "Selected period: 2026-03-01 - 2026-03-08"  # type: ignore[attr-defined]
"""
)


FSM_FLOW_COMMAND_TEMPLATE = Template(
    """from pybotx import Bot, HandlerCollector, IncomingMessage

from $fsm_module_prefix.$module_name import $start_function_name


collector = HandlerCollector()


@collector.command($command_literal, description=$description_literal)
async def $handler_name(message: IncomingMessage, bot: Bot) -> None:
    await $start_function_name(message, bot)
"""
)


FSM_FLOW_MODULE_TEMPLATE = Template(
    """from enum import Enum, auto

from pybotx import Bot, IncomingMessage
from pybotx_fsm import FSMCollector


class $states_enum_name(Enum):
    ENTER_VALUE = auto()
    CONFIRM_VALUE = auto()


fsm = FSMCollector($states_enum_name)


async def $start_function_name(message: IncomingMessage, bot: Bot) -> None:
    await message.state.fsm.change_state($states_enum_name.ENTER_VALUE)
    await bot.answer_message($initial_prompt_literal)


@fsm.on($states_enum_name.ENTER_VALUE)
async def enter_value(message: IncomingMessage, bot: Bot) -> None:
    value = message.body.strip()
    if not value:
        await bot.answer_message("Value can't be empty. Try again.")
        return

    await message.state.fsm.change_state($states_enum_name.CONFIRM_VALUE, value=value)
    await bot.answer_message(
        f"Confirm $display_name_lower value: {value}. Reply with yes or no.",
    )


@fsm.on($states_enum_name.CONFIRM_VALUE)
async def confirm_value(message: IncomingMessage, bot: Bot) -> None:
    decision = message.body.strip().lower()
    value = message.state.fsm_storage.value

    if decision in {"yes", "y"}:
        await message.state.fsm.drop_state()
        $completion_statement
        return

    if decision in {"no", "n"}:
        await message.state.fsm.change_state($states_enum_name.ENTER_VALUE)
        await bot.answer_message($initial_prompt_literal)
        return

    await bot.answer_message("Reply with yes or no.")
"""
)


FSM_FLOW_TEST_TEMPLATE = Template(
    """from collections.abc import Callable

from pybotx import Bot, IncomingMessage


async def test_${module_name}_fsm_flow(
    bot: Bot,
    incoming_message_factory: Callable[..., IncomingMessage],
) -> None:
    await bot.async_execute_bot_command(incoming_message_factory(body=$command_literal))
    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        $initial_prompt_literal,
    )

    bot.answer_message.reset_mock()  # type: ignore[attr-defined]
    await bot.async_execute_bot_command(
        incoming_message_factory(body="sample-value"),
    )
    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        "Confirm $display_name_lower value: sample-value. Reply with yes or no.",
    )

    bot.answer_message.reset_mock()  # type: ignore[attr-defined]
    await bot.async_execute_bot_command(incoming_message_factory(body="yes"))
    bot.answer_message.assert_awaited_once_with(  # type: ignore[attr-defined]
        $completion_assert_literal,
    )
"""
)


DOCKERFILE_TEMPLATE = Template(
    """FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app
COPY . .

RUN uv sync --no-dev

CMD ["uv", "run", "uvicorn", "$package_name.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
)


DOCKER_COMPOSE_TEMPLATE = Template(
    """services:
  bot:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
"""
)
