"""Definition of Starlette application that is mock for BotX API."""

from typing import Any, Callable, Dict, List, Sequence, Tuple, Type

from molten import App, JSONParser, Route, Settings, SettingsComponent

from botx.clients.methods.base import BotXMethod
from botx.testing.botx_mock.wsgi.errors import error_middleware
from botx.testing.botx_mock.wsgi.routes.bots import get_token
from botx.testing.botx_mock.wsgi.routes.chats import (
    get_info,
    post_add_user,
    post_create,
    post_remove_user,
    post_stealth_disable,
    post_stealth_set,
)
from botx.testing.botx_mock.wsgi.routes.command import post_command_result
from botx.testing.botx_mock.wsgi.routes.events import post_edit_event
from botx.testing.botx_mock.wsgi.routes.notification import (
    post_notification,
    post_notification_direct,
)
from botx.testing.botx_mock.wsgi.routes.users import (
    get_by_email,
    get_by_huid,
    get_by_login,
)
from botx.testing.typing import APIMessage, APIRequest

_ENDPOINTS: Tuple[Callable[..., Any], ...] = (
    # V2
    # bots
    get_token,
    # V3
    # chats
    get_info,
    post_add_user,
    post_remove_user,
    post_stealth_set,
    post_stealth_disable,
    post_create,
    # command
    post_command_result,
    # events
    post_edit_event,
    # notification
    post_notification,
    post_notification_direct,
    # users
    get_by_huid,
    get_by_email,
    get_by_login,
)


def _create_molten_routes() -> Sequence[Route]:
    routes = []

    for endpoint in _ENDPOINTS:
        routes.append(
            Route(
                endpoint.method.__url__,  # type: ignore  WPS609
                endpoint,
                method=endpoint.method.__method__,  # type: ignore  WPS609
            ),
        )

    return routes


def get_botx_wsgi_api(
    messages: List[APIMessage],
    requests: List[APIRequest],
    errors: Dict[Type[BotXMethod], Tuple[int, Any]],
) -> App:
    """Generate BotX API mock.

    Arguments:
        messages: list of message that were sent from bot and should be extended.
        requests: all requests that were sent from bot.
        errors: errors to be generated by mocked API.

    Returns:
        Generated BotX API mock for using with httpx.
    """
    return App(
        components=[
            SettingsComponent(
                Settings(messages=messages, requests=requests, errors=errors),
            ),
        ],
        routes=list(_create_molten_routes()),
        middleware=[error_middleware],
        parsers=[JSONParser()],
    )
