#!/usr/bin/env bash

set -e

# Sort imports one per line, so autoflake can remove unused imports
isort --recursive  --force-single-line-imports bot

autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place bot
black bot
isort --recursive bot

isort --recursive --thirdparty=botx bot
