#!/usr/bin/env bash

set -e

temp_dir_path=$(mktemp -d "snippetsXXXX")

index=0
while IFS= read -d '' -r snippet || [[ -n "${snippet}" ]]; do
  printf "%s" "${snippet}" > "${temp_dir_path}/snippet${index}.py"
  index=$((index+1))
done < <(grep -Pzo '(?s)(?<=```python\n).*?(?=```)' README.md);

black --check --diff "${temp_dir_path}"
isort --profile black --check-only "${temp_dir_path}"
mypy "${temp_dir_path}"
flake8 "${temp_dir_path}"

rm -rf "${temp_dir_path}"
