#!/usr/bin/env bash

set -e

snippets_dir_path=".snippets"

rm -rf "${snippets_dir_path}"
mkdir "${snippets_dir_path}"

snippet_number=1
while IFS= read -d '' -r snippet || [[ -n "${snippet}" ]]; do
  printf "%s" "${snippet}" \
    > "${snippets_dir_path}/snippet${snippet_number}.py"
  snippet_number=$((snippet_number+1))
done < <(grep -Pzo '(?s)(?<=```python\n).*?(?=```)' README.md);

mypy "${snippets_dir_path}"
ruff check "${snippets_dir_path}" --ignore F405

rm -rf "${snippets_dir_path}"
