#!/usr/bin/env bash

set -e

# Sort imports one per line, so autoflake can remove unused imports
isort --recursive  --force-single-line-imports botx tests docs/src

autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place docs/src/ botx tests --exclude=__init__.py
black botx tests docs/src
isort --recursive botx tests

# sort botx imports as it third-party library
isort --recursive --thirdparty=botx docs/src

