#!/usr/bin/env bash

set -ex

autoflake --recursive --in-place \
  --remove-all-unused-imports \
  --ignore-init-module-imports \
  pybotx tests
isort --profile black pybotx tests
black pybotx tests

find pybotx -type f -name "*.py" | xargs add-trailing-comma --py36-plus --exit-zero-even-if-changed
find tests -type f -name "*.py" | xargs add-trailing-comma --py36-plus --exit-zero-even-if-changed

# This `black` is needed again in order to transfer parameters/arguments to new lines
# after inserting commas.
# The first `black` won't be able to transfer parameters/arguments to new lines because
# there is no comma at the end of the line.
# Inserting commas must be after the first `black`, so that there is one new line break,
# if the line is out of max-line-length.
black pybotx tests > /dev/null
