from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

PREFERRED_ORDER = (
    "bots",
    "chats",
    "events",
    "files",
    "metrics",
    "notifications",
    "openid",
    "smartapps",
    "stickers",
    "users",
)

ALIAS_MAP = {
    "mertics": "metrics",
}

CLASS_NAME_OVERRIDES = {
    "openid": "OpenIdApiMixin",
    "smartapps": "SmartAppsApiMixin",
}

@dataclass(frozen=True)
class Facet:
    module: str
    class_name: str


def _snake_to_camel(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def _collect_facets(client_dir: Path) -> list[Facet]:
    facets: list[Facet] = []
    for child in client_dir.iterdir():
        if not child.is_dir():
            continue
        if child.name.startswith("__"):
            continue
        if not child.name.endswith("_api"):
            continue

        base = child.name[: -len("_api")]
        module = ALIAS_MAP.get(base, base)
        class_name = CLASS_NAME_OVERRIDES.get(
            module,
            f"{_snake_to_camel(module)}ApiMixin",
        )
        facets.append(Facet(module=module, class_name=class_name))
    return facets


def _sorted_facets(facets: Iterable[Facet]) -> list[Facet]:
    by_name = {facet.module: facet for facet in facets}
    ordered: list[Facet] = []
    for name in PREFERRED_ORDER:
        facet = by_name.pop(name, None)
        if facet is not None:
            ordered.append(facet)
    ordered.extend(by_name[name] for name in sorted(by_name))
    return ordered


def _ensure_stub_modules(botx_api_dir: Path, facets: Iterable[Facet]) -> None:
    for facet in facets:
        path = botx_api_dir / f"{facet.module}.py"
        if path.exists():
            continue
        path.write_text(
            "".join(
                (
                    "from __future__ import annotations\n\n",
                    f"class {facet.class_name}:\n",
                    "    pass\n",
                )
            ),
            encoding="utf-8",
        )


def _render_init(facets: Iterable[Facet]) -> str:
    facet_list = list(facets)
    imports = "\n".join(
        f"from pybotx.infrastructure.botx_api.{facet.module} import {facet.class_name}"
        for facet in facet_list
    )
    mixins = "".join(f"    {facet.class_name},\n" for facet in facet_list)
    imports_block = f"{imports}\n\n\n" if imports else "\n\n"

    return "".join(
        (
            "# This file is auto-generated by scripts/generate_botx_facets.py\n",
            "# Do not edit manually.\n",
            "from __future__ import annotations\n\n",
            "from pybotx.domain.ports.botx_api import BotXApiPort\n\n",
            "from pybotx.infrastructure.botx_api.base import BotXApiBase\n",
            "from pybotx.infrastructure.botx_api.method_factory import BotXApiMethodFactory\n",
            imports_block,
            "class HttpBotXApi(\n",
            "    BotXApiBase,\n",
            mixins,
            "    BotXApiPort,\n",
            "):\n",
            "    pass\n\n\n",
            "__all__ = (\"BotXApiMethodFactory\", \"HttpBotXApi\")\n",
        )
    )


def _write_if_changed(path: Path, content: str, *, check: bool) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return
    if check:
        raise SystemExit(f"{path} is out of date. Run scripts/generate_botx_facets.py")
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    client_dir = repo_root / "pybotx" / "infrastructure" / "client"
    botx_api_dir = repo_root / "pybotx" / "infrastructure" / "botx_api"
    init_path = botx_api_dir / "__init__.py"

    facets = _sorted_facets(_collect_facets(client_dir))

    if not args.check:
        _ensure_stub_modules(botx_api_dir, facets)

    init_content = _render_init(facets)
    _write_if_changed(init_path, init_content, check=args.check)


if __name__ == "__main__":
    main()
