# This file is auto-generated by scripts/generate_botx_facets.py
# Do not edit manually.
from __future__ import annotations

from pybotx.domain.ports.botx_api import BotXApiPort

from pybotx.infrastructure.botx_api.base import BotXApiBase
from pybotx.infrastructure.botx_api.method_factory import BotXApiMethodFactory
from pybotx.infrastructure.botx_api.bots import BotsApiMixin
from pybotx.infrastructure.botx_api.chats import ChatsApiMixin
from pybotx.infrastructure.botx_api.events import EventsApiMixin
from pybotx.infrastructure.botx_api.files import FilesApiMixin
from pybotx.infrastructure.botx_api.metrics import MetricsApiMixin
from pybotx.infrastructure.botx_api.notifications import NotificationsApiMixin
from pybotx.infrastructure.botx_api.openid import OpenIdApiMixin
from pybotx.infrastructure.botx_api.smartapps import SmartAppsApiMixin
from pybotx.infrastructure.botx_api.stickers import StickersApiMixin
from pybotx.infrastructure.botx_api.users import UsersApiMixin


class HttpBotXApi(
    BotXApiBase,
    BotsApiMixin,
    ChatsApiMixin,
    EventsApiMixin,
    FilesApiMixin,
    MetricsApiMixin,
    NotificationsApiMixin,
    OpenIdApiMixin,
    SmartAppsApiMixin,
    StickersApiMixin,
    UsersApiMixin,
    BotXApiPort,
):
    pass


__all__ = ("BotXApiMethodFactory", "HttpBotXApi")
