"""Module with test data content for files."""

JPG_DATA = "data:image/jpeg;base64,Lg=="
JPEG_DATA = "data:image/jpeg;base64,Lg=="
GIF_DATA = "data:image/gif;base64,Lg=="
PNG_DATA = "data:image/png;base64,Lg=="
DOC_DATA = "data:application/msword;base64,Lg=="
DOCX_DATA = "data:application/vnd.openxmlformats-officedocument.wordprocessingml.document;base64,Lg=="
XLS_DATA = "data:application/vnd.ms-excel;base64,Lg=="
XLSX_DATA = (
    "data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,Lg=="
)
TXT_DATA = "data:text/plain;base64,Lg=="
PDF_DATA = "data:application/pdf;base64,Lg=="
HTML_DATA = "data:text/html;base64,Lg=="
JSON_DATA = "data:application/json;base64,Lg=="
SIG_DATA = "data:application/pgp-signature;base64,Lg=="
PPT_DATA = "data:application/vnd.ms-powerpoint;base64,Lg=="
PPTX_DATA = "data:application/vnd.openxmlformats-officedocument.presentationml.presentation;base64,Lg=="
MP3_DATA = "data:audio/mpeg;base64,Lg=="
MP4_DATA = "data:video/mp4;base64,Lg=="
GZ_DATA = "data:text/plain;base64,Lg=="
TGZ_DATA = "data:application/x-tar;base64,Lg=="
ZIP_DATA = "data:application/zip;base64,Lg=="
RAR_DATA = "data:application/vnd.rar;base64,Lg=="
