name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        id: cache-poetry
        with:
          path: ~/.cache/pip
          key: get-poetry-${{ runner.os }}-py-${{ matrix.python-version }}
      - name: Install poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          pip install poetry==1.0
          poetry config virtualenvs.in-project true
      - uses: actions/cache@v1
        id: cache-deps-extras
        with:
          path: .venv
          key: venv-${{ runner.os }}-py-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-deps-extras.outputs.cache-hit != 'true'
        run: |
          poetry install --extras docs
      - name: Build MkDocs for GitHub Pages
        run: |
          source .venv/bin/activate
          ./scripts/build-docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site