name: Python application
on: push
jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7.12, 3.8.12, 3.9.9, 3.10.1]

    steps:
      - name: Setup dependencies
        uses: ExpressApp/github-actions-poetry@v0.1
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "1.1.12"

      - name: Run tests
        env:
          BOT_CREDENTIALS: ${{ secrets.END_TO_END_TESTS_BOT_CREDENTIALS }}
        run: |
          source .venv/bin/activate
          ./scripts/test --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Setup dependencies
        uses: ExpressApp/github-actions-poetry@v0.1

      - name: Run linters
        run: |
          source .venv/bin/activate
          ./scripts/lint
