name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry==1.0
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run tests
        run: |
          source .venv/bin/activate
          ./scripts/test --cov-report=xml
      - uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
